IMPORT LIBRARY

In [1]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

from pyspark.ml.feature import (
    RegexTokenizer,
    CountVectorizer,
    IDF
)

from pyspark.sql.types import ArrayType, StringType
from pyspark.ml.stat import Summarizer

import pandas as pd
import numpy as np
from pathlib import Path
from deep_translator import GoogleTranslator
import os

In [2]:
BASE_DIR = Path.cwd()

while BASE_DIR.name != "Final_Project":

    BASE_DIR = BASE_DIR.parent


os.chdir(BASE_DIR)

print(os.getcwd())

FINAL_DIR = BASE_DIR / "data" / "final"
FINAL_DIR.mkdir(parents=True,exist_ok=True)

c:\Users\sever\Documents\Project_Coolyeah\Lab_MCI\Final_Project

In [3]:
spark = SparkSession.builder \
    .master("local[*]") \
    .appName("TFIDFAnalysis") \
    .getOrCreate()

DATA LOADING

In [4]:
cleaned_master_df = spark.read.parquet(
    "data/final/master_cleaned"
)

cleaned_master_df.limit(20).toPandas()

,order_id,review_score,review_comment_message,sentiment,product_category_name_english,delivery_delay_days,delivery_status,customer_state,seller_id,seller_state,same_state_shipping
0,10c3c7fea20a1ed15c6e55e90b3fb084,1,Não recebi o produto e nem meu dinheiro de volta,negative,perfumery,17,late,SP,3c7c4a49ec3c6550809089c6a2ca9370,SP,1
1,a3e4fb1d4c4c04deb731bae74f190339,5,Produto de ótima qualidade e chegou antes do p...,positive,sports_leisure,-21,early,AP,376a891762bbdecbc02b4b6adec3fdda,GO,0
2,d7e87a1388d89fa6d7841f32c6954c2e,1,Foram pedidos 2 unidades e recebemos só 1,negative,health_beauty,-25,early,SP,8444e55c1f13cd5c179851e5ca5ebd00,MG,0
3,741bffa3ccd9486d8050c172ea085d43,5,no_review,positive,watches_gifts,-34,early,PR,d921b68bf747894be13a97ae52b0f386,MG,0
4,c6eb7d8978a0d7a7e592ef611e4daf04,5,no_review,positive,fashion_underwear_beach,-19,early,MG,a6fe7de3d16f6149ffe280349a8535a0,SP,0
5,9e51155c4d15c5f62e0b309826c25a02,5,no_review,positive,garden_tools,-2,early,RJ,1f50f920176fa81dab994f9023523100,SP,0
6,20d07181f8cec8c3fa51212c7dd926ea,5,no_review,positive,cool_stuff,-38,early,ES,8444e55c1f13cd5c179851e5ca5ebd00,MG,0
7,dae4fcb62b78ccf2ff3ac4d49113a8f5,5,super recomendo produto profissional de qualidade,positive,housewares,-17,early,CE,aced59e9b31ef866a94f9e7f29d8d418,SP,0
8,4e839b1ce670c701bd83a9d9aeb58969,5,no_review,positive,sports_leisure,-14,early,SP,41da412d33e8da4f22baf55cb1bde82c,ES,0
9,620b3433404a08b299e50c716866a4d1,5,no_review,positive,cool_stuff,-13,early,PE,7a67c85e85bb2ce8582c35f2203ad736,SP,0
10,edf97e2ce9f13188f1f70288901d707a,5,no_review,positive,housewares,-5,early,SP,138dbe45fc62f1e244378131a6801526,SP,1
11,e0788e95b53fbcfd9955d96e0fcade45,5,no_review,positive,musical_instruments,-4,early,SP,6d66611d7c44cc30ce351abc49a68421,SP,1
12,a5bb475db1b4bcf9aa10cda733fcda10,5,no_review,positive,sports_leisure,-41,early,SP,4fe2f67634d00c021aa01f96b6f2d68e,PR,0
13,2e8b2390e7734d4477db1b7e1fdc38d7,3,"mas fiquei super chateada, pq fiz um pedido co...",neutral,furniture_decor,-13,early,CE,f2336e113377dd21c744d9c4fc8293a9,SP,0
14,df2d910b8b5e5f461f67043489f9569d,1,o carrinho veio com defeito.,negative,cool_stuff,-10,early,PE,48436dade18ac8b2bce089ec2a041202,SP,0
15,825197d9865f5523eb079605067c8fed,4,no_review,positive,agro_industry_and_commerce,-4,early,SP,d297f1055de2956aedfd3b04113dce3e,SP,1
16,e664de6693c1c46a03c7a561518546a6,5,no_review,positive,housewares,-8,early,SP,138dbe45fc62f1e244378131a6801526,SP,1
17,1831a71825a5c61b74815e606e7db61e,4,Muito bom o produto,positive,housewares,-34,early,PA,fffd5413c0700ac820c7069d66d98c89,SP,0
18,b2583516574ac20b8b3ee77ff7418f66,5,no_review,positive,furniture_decor,-17,early,SP,20cb7c2fde3e5bf10f0bbe7394e1c6a9,PR,0
19,c2cd6ce44609af75d061dfab2f67179c,5,otimo de se comprar,positive,bed_bath_table,-15,early,MG,d1c281d3ae149232351cd8c8cc885f0d,SP,0

DATA SELECTION

In [5]:
negative_reviews_df = cleaned_master_df.filter(
    col("review_score") <= 2
)

DATA CLEANING

In [6]:
print(f"Old data total: {negative_reviews_df.count()}")
negative_reviews_df = negative_reviews_df.filter(
    col("review_comment_message") != "no_review"
)

negative_reviews_df = negative_reviews_df.filter(
    trim(col("review_comment_message")) != ""
)

print(f"Cleaned data total: {negative_reviews_df.count()}")
negative_reviews_df.limit(10).toPandas()

Old data total: 12637
Cleaned data total: 9570

,order_id,review_score,review_comment_message,sentiment,product_category_name_english,delivery_delay_days,delivery_status,customer_state,seller_id,seller_state,same_state_shipping
0,10c3c7fea20a1ed15c6e55e90b3fb084,1,Não recebi o produto e nem meu dinheiro de volta,negative,perfumery,17,late,SP,3c7c4a49ec3c6550809089c6a2ca9370,SP,1
1,d7e87a1388d89fa6d7841f32c6954c2e,1,Foram pedidos 2 unidades e recebemos só 1,negative,health_beauty,-25,early,SP,8444e55c1f13cd5c179851e5ca5ebd00,MG,0
2,df2d910b8b5e5f461f67043489f9569d,1,o carrinho veio com defeito.,negative,cool_stuff,-10,early,PE,48436dade18ac8b2bce089ec2a041202,SP,0
3,1a292836ced1aa222199c34c883f404e,1,o produto não chegou,negative,stationery,7,late,SP,3d871de0142ce09b7081e2b9d1733cb1,SP,1
4,9c37d94303e95d233a4608dabc34f802,1,Produto diferente da foto.,negative,construction_tools_construction,-13,early,SP,8648b1e89e9b349e32d3741b30ec737e,SP,1
5,33dea0203a24cd38fb9a7f8ee4bbe0ee,2,"Comprei por um capacete no tamanho G, claramen...",negative,auto,-9,early,SP,33ac3e28642ab8bda860a2f693000e78,SP,1
6,3f6da1442aba80bcf61179602dfab9ca,1,Produto com atraso. Não por causa de greve de ...,negative,auto,6,late,BA,3db66a856d18a9cba7c9241fc5221c50,MG,0
7,ad263bc9111c1e0cbb780c4b7c1009e6,2,Correio não entregou na minha residência tive ...,negative,electronics,-5,early,PA,128639473a139ac0f3e5f5ade55873a5,PR,0
8,312bfb221da51864b9fc4b361542ee5b,1,Produto chegou com risco e manchado.,negative,watches_gifts,-20,early,SP,966cb4760537b1404caedd472cc610a5,SP,1
9,b73bbac6285251dbf2dd01842e0ce0de,1,Ainda não recebi o produto nem qualquer satisf...,negative,air_conditioning,33,late,RJ,15aac934c58d886785ac1b17953ea898,ES,0

DATA NORMALIZATION

In [7]:
negative_reviews_df = negative_reviews_df.withColumn(
    "review_comment_message",
    trim(
        regexp_replace(
            regexp_replace(
                regexp_replace(
                    lower(
                        col("review_comment_message")
                    ),
                    r"\n|\t", " "
                ),
                r"[^a-zA-ZÀ-ÿ\s]",""
            ),
            r"\s+", " "
        )
    )
)

In [8]:
negative_reviews_df.limit(20).toPandas()

,order_id,review_score,review_comment_message,sentiment,product_category_name_english,delivery_delay_days,delivery_status,customer_state,seller_id,seller_state,same_state_shipping
0,10c3c7fea20a1ed15c6e55e90b3fb084,1,não recebi o produto e nem meu dinheiro de volta,negative,perfumery,17,late,SP,3c7c4a49ec3c6550809089c6a2ca9370,SP,1
1,d7e87a1388d89fa6d7841f32c6954c2e,1,foram pedidos unidades e recebemos só,negative,health_beauty,-25,early,SP,8444e55c1f13cd5c179851e5ca5ebd00,MG,0
2,df2d910b8b5e5f461f67043489f9569d,1,o carrinho veio com defeito,negative,cool_stuff,-10,early,PE,48436dade18ac8b2bce089ec2a041202,SP,0
3,1a292836ced1aa222199c34c883f404e,1,o produto não chegou,negative,stationery,7,late,SP,3d871de0142ce09b7081e2b9d1733cb1,SP,1
4,9c37d94303e95d233a4608dabc34f802,1,produto diferente da foto,negative,construction_tools_construction,-13,early,SP,8648b1e89e9b349e32d3741b30ec737e,SP,1
5,33dea0203a24cd38fb9a7f8ee4bbe0ee,2,comprei por um capacete no tamanho g clarament...,negative,auto,-9,early,SP,33ac3e28642ab8bda860a2f693000e78,SP,1
6,3f6da1442aba80bcf61179602dfab9ca,1,produto com atraso não por causa de greve de c...,negative,auto,6,late,BA,3db66a856d18a9cba7c9241fc5221c50,MG,0
7,ad263bc9111c1e0cbb780c4b7c1009e6,2,correio não entregou na minha residência tive ...,negative,electronics,-5,early,PA,128639473a139ac0f3e5f5ade55873a5,PR,0
8,312bfb221da51864b9fc4b361542ee5b,1,produto chegou com risco e manchado,negative,watches_gifts,-20,early,SP,966cb4760537b1404caedd472cc610a5,SP,1
9,b73bbac6285251dbf2dd01842e0ce0de,1,ainda não recebi o produto nem qualquer satisf...,negative,air_conditioning,33,late,RJ,15aac934c58d886785ac1b17953ea898,ES,0
10,3611e9793009655c4d1350655211953c,2,prazo para o dia e não foi entregue,negative,furniture_decor,10,late,RJ,1554a68530182680ad5c8b042c3ab563,MG,0
11,e61f21c687d3607657f3799b5e182916,1,na foto mostra um produto quando chega e outro...,negative,auto,-1,early,RJ,f5b44895715ddfe3087dc414f30268f3,SP,0
12,c55c2cba4bd6069c80c2531fe9a9188a,1,não recebi os produtos corretamente faltou uma...,negative,toys,-2,early,RJ,7aa4334be125fcdd2ba64b3180029f14,SP,0
13,139cef5540861404dd35fe65000fda2e,1,recomendo as lannister mas o parceiro é péssim...,negative,garden_tools,16,late,RJ,1f50f920176fa81dab994f9023523100,SP,0
14,d677832afa9db3b30b1ae12129ef4018,1,enviei um comunicado para as lannister sobre o...,negative,computers_accessories,-16,early,BA,4e922959ae960d389249c378d1c939f5,SP,0
15,75156818c2863d3be5ab7b08e728e43d,1,bom dia recebi so cortina deveria ter vindo ju...,negative,bed_bath_table,-13,early,RS,da8622b14eb17ae2831f4ac5b9dab84a,SP,0
16,065881aa6f8059a970c8fd9947f717e4,1,gastei com o frete de reais é gastei também pa...,negative,perfumery,-10,early,RJ,3c7c4a49ec3c6550809089c6a2ca9370,SP,0
17,4671913802b0033db963ffec94dc5bbe,1,não recebi o produto é não consigo rastrear o ...,negative,stationery,5,late,RJ,3d871de0142ce09b7081e2b9d1733cb1,SP,0
18,001d8f0e34a38c37f7dba2a37d4eba8b,1,entrega prometida dia não havia recebido ainda,negative,health_beauty,2,late,SP,f4aba7c0bca51484c30ab7bdc34bcdd1,SP,1
19,df9ad58c9ee5c31a5a9e19eea2acc369,2,não gostei do produto,negative,bed_bath_table,0,on_time,RJ,391fc6631aebcf3004804e51b40bcf1e,SP,0

TEXT PREPROCESSING

In [9]:
tokenizer = RegexTokenizer(
    inputCol="review_comment_message",
    outputCol="words",
    pattern="\\s+"
)

df_token = tokenizer.transform(negative_reviews_df)

df_token.select("review_comment_message", "words").limit(10).toPandas()

,review_comment_message,words
0,não recebi o produto e nem meu dinheiro de volta,"[não, recebi, o, produto, e, nem, meu, dinheir..."
1,foram pedidos unidades e recebemos só,"[foram, pedidos, unidades, e, recebemos, só]"
2,o carrinho veio com defeito,"[o, carrinho, veio, com, defeito]"
3,o produto não chegou,"[o, produto, não, chegou]"
4,produto diferente da foto,"[produto, diferente, da, foto]"
5,comprei por um capacete no tamanho g clarament...,"[comprei, por, um, capacete, no, tamanho, g, c..."
6,produto com atraso não por causa de greve de c...,"[produto, com, atraso, não, por, causa, de, gr..."
7,correio não entregou na minha residência tive ...,"[correio, não, entregou, na, minha, residência..."
8,produto chegou com risco e manchado,"[produto, chegou, com, risco, e, manchado]"
9,ainda não recebi o produto nem qualquer satisf...,"[ainda, não, recebi, o, produto, nem, qualquer..."

TD-IDF IMPLEMENTATION

In [10]:
cv = CountVectorizer(
    inputCol="words",
    outputCol="tf",
    vocabSize=20000
)
cv_model = cv.fit(df_token)
df_tf = cv_model.transform(df_token)


idf = IDF(inputCol="tf", outputCol="tfidf")
idf_model = idf.fit(df_tf)
df_tfidf = idf_model.transform(df_tf)


idf_values = idf_model.idf.toArray()
vocab = cv_model.vocabulary
threshold = 4.0


important_words = [
    vocab[i] for i, val in enumerate(idf_values)
    if val > threshold
]

print("Important Words Total:", len(important_words))
print("Example:", important_words[:20])

Important Words Total: 9589
Example: ['caixa', 'kit', 'unidades', 'frete', 'relógio', 'valor', 'so', 'data', 'devolver', 'fazer', 'preciso', 'consigo', 'ninguém', 'embalagem', 'correio', 'antes', 'péssima', 'consta', 'demora', 'chegar']

SIGNATURE KEYWORD EXTRACTION

In [11]:
def extract_keywords(tfidf_vector):
    if tfidf_vector is None: return []

    arr = tfidf_vector.toArray()

    nonzero_indices = np.where(arr > 0)[0]

    valid_candidates = [
        i for i in nonzero_indices
        if idf_values[i] > threshold and len(vocab[i]) > 2
    ]
    sorted_keywords = sorted(valid_candidates, key=lambda i: arr[i], reverse=True)

    return [vocab[i] for i in sorted_keywords[:5]]

In [12]:
negative_words = [

    "defeito",
    "quebrado",
    "quebrada",
    "atraso",
    "atrasada",
    "faltando",
    "erro",
    "ruim",
    "péssimo",
    "demora",
    "danificado",
    "problema",
    "cancelado",
    "fraco",
    "sujo",
    "enganado",
    "defeituoso",
    "incompleto",
    "rasgado",
    "amassado",
    "desligado",
    "vazando",
    "errado",
    "trincado",
    "reclamação"

]

In [13]:
df_category_grouped = (

    df_tfidf.groupBy(
        "product_category_name_english"
    )
    .agg(
        Summarizer.mean(
            col("tfidf")
        ).alias("avg_tfidf")
    )
)

category_rows = (
    df_category_grouped.collect()
)

In [14]:
results = []

for row in category_rows:

    category = row[
        "product_category_name_english"
    ]

    tfidf_vector = row[
        "avg_tfidf"
    ]

    arr = tfidf_vector.toArray()

    nonzero_indices = np.where(
        arr > 0
    )[0]

    valid_candidates = [

        i for i in nonzero_indices

        if (

            idf_values[i] > threshold

            and vocab[i] in negative_words
        )
    ]


    sorted_keywords = sorted(

        valid_candidates,

        key=lambda i: arr[i],

        reverse=True
    )


    top_keywords = [

        vocab[i]

        for i in sorted_keywords[:5]
    ]


    results.append({

        "category": category,

        "negative_keywords": top_keywords
    })

result_pd = pd.DataFrame(
    results
)

result_pd.head(20)

,category,negative_keywords
0,art,[fraco]
1,flowers,[]
2,home_construction,"[danificado, demora, amassado, quebrado, ruim]"
3,fashion_male_clothing,[]
4,kitchen_dining_laundry_garden_furniture,"[fraco, erro, atraso]"
5,small_appliances,"[amassado, reclamação, quebrado, erro, quebrada]"
6,la_cuisine,[]
7,bed_bath_table,"[ruim, péssimo, demora, fraco, atraso]"
8,signaling_and_security,"[erro, fraco, quebrado]"
9,office_furniture,"[rasgado, quebrada, reclamação, péssimo, atraso]"
10,computers,[amassado]
11,watches_gifts,"[péssimo, atraso, ruim, fraco, quebrado]"
12,auto,"[demora, atraso, ruim, quebrado, reclamação]"
13,fashion_bags_accessories,"[péssimo, demora, amassado, atrasada, fraco]"
14,construction_tools_lights,"[amassado, atrasada, ruim]"
15,cool_stuff,"[quebrado, atraso, demora, reclamação, péssimo]"
16,food,"[vazando, quebrado, atraso]"
17,computers_accessories,"[demora, atraso, reclamação, ruim, enganado]"
18,perfumery,"[péssimo, demora, quebrado, cancelado, amassado]"
19,pet_shop,"[incompleto, reclamação, péssimo, atraso, demora]"

TRANSLATE RESULT

In [15]:
def translate_keywords(keyword_list):

    translated = []

    for word in keyword_list:

        try:

            translated_word = GoogleTranslator(
                source="pt",
                target="en"
            ).translate(word)

            translated.append(translated_word)

        except:

            translated.append(word)

    return translated

In [16]:
translated_result_pd = result_pd.copy()

translated_result_pd["translated_keywords"] = translated_result_pd["negative_keywords"].apply(translate_keywords)

In [17]:
translated_result_pd.head(20)

,category,negative_keywords,translated_keywords
0,art,[fraco],[weak]
1,flowers,[],[]
2,home_construction,"[danificado, demora, amassado, quebrado, ruim]","[damaged, delay, kneaded, broken, bad]"
3,fashion_male_clothing,[],[]
4,kitchen_dining_laundry_garden_furniture,"[fraco, erro, atraso]","[weak, error, delay]"
5,small_appliances,"[amassado, reclamação, quebrado, erro, quebrada]","[kneaded, complaint, broken, error, broken]"
6,la_cuisine,[],[]
7,bed_bath_table,"[ruim, péssimo, demora, fraco, atraso]","[bad, bad, delay, weak, delay]"
8,signaling_and_security,"[erro, fraco, quebrado]","[error, weak, broken]"
9,office_furniture,"[rasgado, quebrada, reclamação, péssimo, atraso]","[scratched, broken, complaint, bad, delay]"
10,computers,[amassado],[kneaded]
11,watches_gifts,"[péssimo, atraso, ruim, fraco, quebrado]","[bad, delay, bad, weak, broken]"
12,auto,"[demora, atraso, ruim, quebrado, reclamação]","[delay, delay, bad, broken, complaint]"
13,fashion_bags_accessories,"[péssimo, demora, amassado, atrasada, fraco]","[bad, delay, kneaded, late, weak]"
14,construction_tools_lights,"[amassado, atrasada, ruim]","[kneaded, late, bad]"
15,cool_stuff,"[quebrado, atraso, demora, reclamação, péssimo]","[broken, delay, delay, complaint, bad]"
16,food,"[vazando, quebrado, atraso]","[leaking, broken, delay]"
17,computers_accessories,"[demora, atraso, reclamação, ruim, enganado]","[delay, delay, complaint, bad, deceived]"
18,perfumery,"[péssimo, demora, quebrado, cancelado, amassado]","[bad, delay, broken, canceled, kneaded]"
19,pet_shop,"[incompleto, reclamação, péssimo, atraso, demora]","[incomplete, complaint, bad, delay, delay]"

In [18]:
translated_result_pd = translated_result_pd.astype(str)

In [19]:
tfidf_result_df = spark.createDataFrame(
    translated_result_pd[["category", "translated_keywords"]]
)

In [20]:
tfidf_result_df.printSchema()

root
 |-- category: string (nullable = true)
 |-- translated_keywords: string (nullable = true)

In [23]:
os.makedirs("data/final",exist_ok=True)

result_pd.to_csv(
    "data/final/tfidf_keywords.csv",
    index=False
)

print("tfidf_keywords.csv saved")

tfidf_keywords.csv saved